name: donation
description: A Graduation project.

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  flutter_phoenix: ^1.1.1
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  responsive_sizer: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/translations/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri/Amiri-Regular.ttf
        - asset: assets/fonts/amiri/Amiri-BoldItalic.ttf
        - asset: assets/fonts/amiri/Amiri-Italic.ttf
        - asset: assets/fonts/amiri/Amiri-Bold.ttf
          style: normal
