// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwweiYe5U2xlfxGr6RvxZvbDXfncSz3jY',
    appId: '1:295368262040:web:a23514f1eaa07495f3abed',
    messagingSenderId: '295368262040',
    projectId: 'donation-4de07',
    authDomain: 'donation-4de07.firebaseapp.com',
    storageBucket: 'donation-4de07.appspot.com',
    measurementId: 'G-J4FKL9X30F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChQhUaqvcbdUT7AKEq0iCzVjSvxFwGhw',
    appId: '1:295368262040:android:9ee68576ff842b8df3abed',
    messagingSenderId: '295368262040',
    projectId: 'donation-4de07',
    storageBucket: 'donation-4de07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7IIEu1OwvXUQ9BO_JEILqyasWzfLMD4',
    appId: '1:295368262040:ios:d3fc8a21c10f4364f3abed',
    messagingSenderId: '295368262040',
    projectId: 'donation-4de07',
    storageBucket: 'donation-4de07.appspot.com',
    iosBundleId: 'com.ashmawi.donation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt7IIEu1OwvXUQ9BO_JEILqyasWzfLMD4',
    appId: '1:295368262040:ios:d3fc8a21c10f4364f3abed',
    messagingSenderId: '295368262040',
    projectId: 'donation-4de07',
    storageBucket: 'donation-4de07.appspot.com',
    iosBundleId: 'com.ashmawi.donation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwweiYe5U2xlfxGr6RvxZvbDXfncSz3jY',
    appId: '1:295368262040:web:3fbb37c583c90834f3abed',
    messagingSenderId: '295368262040',
    projectId: 'donation-4de07',
    authDomain: 'donation-4de07.firebaseapp.com',
    storageBucket: 'donation-4de07.appspot.com',
    measurementId: 'G-BX9YB1NPJP',
  );
}
